/** Static content for the informational screens (Help, About, Contact, Legal). */

export const FAQ: { q: string; a: string }[] = [
  {
    q: 'How does the AI trip planner work?',
    a: 'Tell us your destination, dates, travellers, budget and vibe. Our AI designs a full day-by-day itinerary with a budget breakdown, highlights, local tips and how to get there — in seconds.',
  },
  {
    q: 'Is AI Travel Planner free to use?',
    a: 'Yes — generating trips, chatting with the AI assistant, joining the community and most features are free. Some third-party bookings may carry their own charges.',
  },
  {
    q: 'What does "Saved" vs "Crafted" mean in My Trips?',
    a: '"Crafted" shows every trip the AI has generated for you. "Saved" shows only the trips you have bookmarked with the Save button on a plan.',
  },
  {
    q: 'How do I share a trip with the community?',
    a: 'Open any plan and tap "Share" on the "Loved this plan?" card. It posts to the community feed where others can like and comment.',
  },
  {
    q: 'Can I message other travellers?',
    a: 'Yes. Find travellers under Explore → search, open their profile, and tap the message icon — or start a chat from your Friends list.',
  },
  {
    q: 'How is my Trust Score calculated?',
    a: 'It reflects your activity and standing in the community — genuine engagement, completed trips and positive interactions raise it.',
  },
  {
    q: 'How does the Safety Center work?',
    a: 'Add emergency contacts, view local safety alerts, and use the SOS button to instantly notify your contacts with your details.',
  },
];

export const ABOUT = {
  tagline: 'Plan smarter. Wander further.',
  body: [
    'AI Travel Planner turns a few simple choices into a complete, personalized journey — powered by AI and shaped by a community of real travellers.',
    'From day-by-day itineraries and smart budgets to shared experiences, group expenses, safety tools and live travel intelligence, everything you need for a great trip lives in one place.',
    'We believe travel should be effortless, social and safe. That belief drives every feature we build.',
  ],
  stats: [
    { value: 'AI', label: 'Powered' },
    { value: '20+', label: 'Features' },
    { value: '1M+', label: 'Destinations' },
  ],
};

export const CONTACT = {
  intro: 'We would love to hear from you — questions, feedback or partnership ideas.',
  email: 'support@aitravelplanner.app',
  items: [
    { label: 'Support', value: 'support@aitravelplanner.app' },
    { label: 'Partnerships', value: 'partners@aitravelplanner.app' },
    { label: 'Press', value: 'press@aitravelplanner.app' },
  ],
};

export const TERMS: { heading: string; body: string }[] = [
  {
    heading: '1. Acceptance of terms',
    body: 'By creating an account or using AI Travel Planner, you agree to these Terms of Service. If you do not agree, please do not use the app.',
  },
  {
    heading: '2. Your account',
    body: 'You are responsible for keeping your login credentials secure and for all activity under your account. Provide accurate information and keep it up to date.',
  },
  {
    heading: '3. Acceptable use',
    body: 'Do not misuse the service: no unlawful, harmful, hateful or spam content, no impersonation, and no attempts to disrupt or reverse-engineer the platform. We may remove content or suspend accounts that violate these rules.',
  },
  {
    heading: '4. AI-generated content',
    body: 'Itineraries, suggestions and estimates are generated by AI for guidance only. Verify important details (prices, visas, opening hours, safety) with official sources before you travel.',
  },
  {
    heading: '5. Bookings & third parties',
    body: 'Some features may link to third-party services (e.g. trains, hotels). Those bookings are subject to the third party’s own terms, pricing and policies. We are not responsible for third-party services.',
  },
  {
    heading: '6. Community content',
    body: 'You own the content you post but grant us a licence to display it in the app. You are responsible for what you share and must have the rights to it.',
  },
  {
    heading: '7. Limitation of liability',
    body: 'The service is provided “as is”. To the fullest extent permitted by law, we are not liable for indirect or consequential losses arising from your use of the app or reliance on AI-generated content.',
  },
  {
    heading: '8. Changes',
    body: 'We may update these terms from time to time. Continued use after changes means you accept the updated terms.',
  },
];

export const PRIVACY: { heading: string; body: string }[] = [
  {
    heading: 'Information we collect',
    body: 'Account details (name, email), your profile and preferences, trips you generate, and content you post. We also process usage data to improve the app.',
  },
  {
    heading: 'How we use your data',
    body: 'To provide and personalize the service — generating trips, powering recommendations, enabling community and messaging features, and keeping the platform safe.',
  },
  {
    heading: 'Authentication',
    body: 'Sign-in is handled by Firebase Authentication. Your password is managed securely by Firebase and is never stored by us in plain text.',
  },
  {
    heading: 'Sharing',
    body: 'We do not sell your personal data. Content you post to the community is visible to other users. Limited data may be processed by service providers (e.g. hosting, image search) solely to run the app.',
  },
  {
    heading: 'Your controls',
    body: 'You can edit your profile, remove content you posted, and manage what you share. Contact us to request deletion of your account and associated data.',
  },
  {
    heading: 'Data security',
    body: 'We use industry-standard measures to protect your data. No system is perfectly secure, so please use a strong password and keep your device safe.',
  },
  {
    heading: 'Contact',
    body: 'Questions about privacy? Reach us at support@aitravelplanner.app.',
  },
];
